In [2]:
import numpy as np
from numpy.random import randint as ri

# 1

In [76]:
vec = np.array([2,3,4,5,6])

In [77]:
vec

array([2, 3, 4, 5, 6])

In [78]:
def out_matrix(v,n,increasing = False):
    mat = []
    if increasing == False:
        for i in range(n):
            mat.append(v**(n-i-1))
    elif increasing == True:
        for i in range(n):
            mat.append(v**i)
    return np.matrix(mat).T   

In [79]:
b = out_matrix(vec,5)
b

matrix([[  16,    8,    4,    2,    1],
        [  81,   27,    9,    3,    1],
        [ 256,   64,   16,    4,    1],
        [ 625,  125,   25,    5,    1],
        [1296,  216,   36,    6,    1]], dtype=int32)

In [80]:
b = out_matrix(vec,5,True)
b

matrix([[   1,    2,    4,    8,   16],
        [   1,    3,    9,   27,   81],
        [   1,    4,   16,   64,  256],
        [   1,    5,   25,  125,  625],
        [   1,    6,   36,  216, 1296]], dtype=int32)

# 2

In [113]:
def mov_avg(arr,k):
    avg = []
    for i in range(len(arr)-k+1):
        avg.append(sum(arr[i:i+k])/k)
    return np.array(avg)
    

In [127]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

In [128]:
 mov_avg(arr,4)

array([25., 35., 45., 55., 65., 75., 85.])

In [129]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3

In [130]:
np.round(mov_avg(arr,k),3)

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])